/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hikingapp.view;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Alex
 */
public class HikeInfoFrame extends javax.swing.JFrame {

    private final HashMap<String, String> HIKE_INFO;
    
    /**
     * 
     * @param hikeInfo 
     */
    public HikeInfoFrame(HashMap<String, String> hikeInfo) {
        this.HIKE_INFO = hikeInfo;
        initComponents();
        //this.hikeTime.setVisible(false);
    }

    public String getHikeName() {
        return "<html><h1>" + this.HIKE_INFO.get("name") + "</h1></html>";
    }
    
    public String getHikeImgUrl() {
        return this.HIKE_INFO.get("imgUrl");
    }
    
    /**
     * Method needs to return a String because it is setting the inside of a JLabel and the required parameter cannot be modified to be a different type.
     * @return A blank string. If the string is filled with a value the value will be printed next to the image.
     */
    public String getHikeImage() {
        try {
            URL url = new URL(getHikeImgUrl());
            Image image = ImageIO.read(url);
            hikeImage.setIcon(new ImageIcon(image));
        } catch(IOException error) {
            System.out.println("An IOException occured in getHikeImage(). " + error);
        }
        return "";
    }
    
    public String getHikeStars() {
        return "Hike rating: " + this.HIKE_INFO.get("stars") + "(" + this.HIKE_INFO.get("starVotes") + ")";
    }
    
    public String getHikeDifficulty() {
        return "Hike difficulty: " + this.HIKE_INFO.get("difficulty");
    }
    
    public String getHikeSummary() {
        return this.HIKE_INFO.get("summary");
    }
    
    public String getHikeAscent() {
        return "Ascent: " + this.HIKE_INFO.get("ascent");
    }
    
    public String getHikeDescent() {
        return "Descent: " + this.HIKE_INFO.get("descent");
    }
    
    public String getHikeHigh() {
        return "High High: " + this.HIKE_INFO.get("high");
    }
    
    public String getHikeLow() {
        return "Hike Low: " + this.HIKE_INFO.get("low");
    }
    
    public String getHikeLocation() {
        return this.HIKE_INFO.get("location");
    }
    
    public String getHikeLength() {
        return "Hike length: " + this.HIKE_INFO.get("length") + " miles";
    }
    
    public String getHikeCondition() {
        return "Hike status: " + this.HIKE_INFO.get("conditionStatus") + ", " + (!this.HIKE_INFO.get("conditionDetails").isEmpty() ? this.HIKE_INFO.get("conditionDetails") : "N/A");
    }
    
    /**
     * Gets t
     * @return 
     */
    public String getHikeMoreInfo() {
        return "To learn more go to this link: " + this.HIKE_INFO.get("url");
    }
    
    /**
     * Gets the date that the hike condition was last updated at.
     * @return A string with the date.
     */
    public String getHikeConditionDate() {
        return "Last updated: " + this.HIKE_INFO.get("conditionDate");
    }
    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hikeName = new javax.swing.JLabel();
        hikeImage = new javax.swing.JLabel();
        hikeStars = new javax.swing.JLabel();
        hikeDifficulty = new javax.swing.JLabel();
        hikeSummary = new javax.swing.JLabel();
        hikeAscent = new javax.swing.JLabel();
        highDescent = new javax.swing.JLabel();
        hikeHigh = new javax.swing.JLabel();
        hikeLow = new javax.swing.JLabel();
        hikeLength = new javax.swing.JLabel();
        hikeLocation = new javax.swing.JLabel();
        hikeCondition = new javax.swing.JLabel();
        hikeStart = new javax.swing.JButton();
        hikeMoreInfo = new javax.swing.JLabel();
        hikeConditionDate = new javax.swing.JLabel();
        hikeTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hikeName.setText(getHikeName());

        hikeImage.setText(getHikeImage());
        hikeImage.setMaximumSize(new java.awt.Dimension(34, 16));

        hikeStars.setText(getHikeStars());

        hikeDifficulty.setText(getHikeDifficulty());

        hikeSummary.setText(getHikeSummary());

        hikeAscent.setText(getHikeAscent());

        highDescent.setText(getHikeDescent());

        hikeHigh.setText(getHikeHigh());

        hikeLow.setText(getHikeLow());

        hikeLength.setText(getHikeLength());

        hikeLocation.setText(getHikeLocation());

        hikeCondition.setText(getHikeCondition());

        hikeStart.setText("Start Hike Timer");
        hikeStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hikeStartActionPerformed(evt);
            }
        });

        hikeMoreInfo.setText(getHikeMoreInfo());

        hikeConditionDate.setText(getHikeConditionDate());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hikeName, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hikeImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hikeSummary)
                            .addComponent(hikeLength)
                            .addComponent(hikeLocation)
                            .addComponent(hikeStart)
                            .addComponent(hikeCondition)
                            .addComponent(hikeMoreInfo)
                            .addComponent(hikeConditionDate)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hikeAscent)
                                    .addComponent(hikeStars)
                                    .addComponent(hikeHigh))
                                .addGap(147, 147, 147)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hikeLow)
                                    .addComponent(hikeDifficulty)
                                    .addComponent(highDescent)))
                            .addComponent(hikeTime))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hikeName)
                .addGap(18, 18, 18)
                .addComponent(hikeImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hikeStars)
                    .addComponent(hikeDifficulty))
                .addGap(18, 18, 18)
                .addComponent(hikeLocation)
                .addGap(42, 42, 42)
                .addComponent(hikeSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(highDescent)
                    .addComponent(hikeAscent))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hikeHigh)
                    .addComponent(hikeLow))
                .addGap(47, 47, 47)
                .addComponent(hikeLength)
                .addGap(28, 28, 28)
                .addComponent(hikeCondition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hikeConditionDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(hikeMoreInfo)
                .addGap(35, 35, 35)
                .addComponent(hikeStart)
                .addGap(18, 18, 18)
                .addComponent(hikeTime)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hikeStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hikeStartActionPerformed
        //this.hikeTime.setVisible(false);
        System.out.println("Started");
        ActionListener taskPerformer = (ActionEvent evt1) -> {
            
            System.out.println("Reading SMTP Info.");
        };
        Timer timer = new Timer(100 ,taskPerformer);
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_hikeStartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel highDescent;
    private javax.swing.JLabel hikeAscent;
    private javax.swing.JLabel hikeCondition;
    private javax.swing.JLabel hikeConditionDate;
    private javax.swing.JLabel hikeDifficulty;
    private javax.swing.JLabel hikeHigh;
    private javax.swing.JLabel hikeImage;
    private javax.swing.JLabel hikeLength;
    private javax.swing.JLabel hikeLocation;
    private javax.swing.JLabel hikeLow;
    private javax.swing.JLabel hikeMoreInfo;
    private javax.swing.JLabel hikeName;
    private javax.swing.JLabel hikeStars;
    private javax.swing.JButton hikeStart;
    private javax.swing.JLabel hikeSummary;
    private javax.swing.JLabel hikeTime;
    // End of variables declaration//GEN-END:variables
}
