package com.hikingapp.view;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 */
public class HikeResultFrame extends javax.swing.JFrame {

    private int hikeTimeSeconds;
    private String hikeImageURL;
    private String hikeLength;
    private String hikeAscent;
    private String hikeDescent;
    private String hikeName;
    private String hikeTimeString;
    
    /**
     * Creates new form HikeResultFrame and instantiates the instance variables.
     */
    public HikeResultFrame(int hikeTimeSeconds, String hikeTimeString, String hikeImageURL, String hikeLength, String hikeAscent, String hikeDescent, String hikeName) {
        this.hikeTimeSeconds = hikeTimeSeconds;
        this.hikeTimeString = hikeTimeString;
        this.hikeImageURL = hikeImageURL;
        this.hikeLength = hikeLength;
        this.hikeAscent = hikeAscent;
        this.hikeDescent = hikeDescent;
        this.hikeName = hikeName;
        initComponents();
    }

    private String getHikeSpeed() {
        return "Average speed: " + Double.toString(Double.parseDouble(this.hikeLength) / this.hikeTimeSeconds) + " MPH";
    }
    
    private String getHikeDistance() {
        return "Total distance hiked: " + this.hikeLength + " miles";
    }
    
    private String getHikeTime() {
        return "Total hike time: " + this.hikeTimeString;
    }
    
    private String getHikeName() {
        return this.hikeName;
    }
    
    private String getHikeImage() {
        try {
            URL url = new URL(hikeImageURL);
            Image imageObject = ImageIO.read(url);
            image.setIcon(new ImageIcon(imageObject));
        } catch(IOException error) {
            System.out.println("An IOException occured in getHikeImage(). " + error);
        }
        return "";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalHikeTime = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        hikeDistance = new javax.swing.JLabel();
        hikeSpeed = new javax.swing.JLabel();
        name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        totalHikeTime.setText(getHikeTime());

        image.setText(getHikeImage());

        hikeDistance.setText(getHikeDistance());

        hikeSpeed.setText(getHikeSpeed());

        name.setText(getHikeName());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalHikeTime)
                    .addComponent(name)
                    .addComponent(image)
                    .addComponent(hikeDistance)
                    .addComponent(hikeSpeed))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalHikeTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name)
                .addGap(9, 9, 9)
                .addComponent(image)
                .addGap(18, 18, 18)
                .addComponent(hikeDistance)
                .addGap(18, 18, 18)
                .addComponent(hikeSpeed)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hikeDistance;
    private javax.swing.JLabel hikeSpeed;
    private javax.swing.JLabel image;
    private javax.swing.JLabel name;
    private javax.swing.JLabel totalHikeTime;
    // End of variables declaration//GEN-END:variables
}
