/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hikingapp.view;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import org.json.JSONObject;
import org.json.JSONException;
import org.json.JSONArray;

/**
 *
 * @author alex
 * @version 1.0 11/12/2020
 */
public class HikesFrame extends javax.swing.JFrame {

    private String address;
    private String postalCode;
    private String city;
    private String state;
    
    /**
     * Creates new form HikesFrame
     */
    public HikesFrame(String address, String postalCode, String city, String state) {
        this.address = address;
        this.postalCode = postalCode;
        this.city = city;
        this.state = state;
        initComponents();
        
    }

    public String getHikeInfo() throws JSONException {
        String apiKey = "200955643-5409210a90c1c5739821d1efae87d2bb";
        String hikeInfo = getApiInfo("https://www.hikingproject.com/data/get-trails?lat=" + getHikePosition()[0] + "&lon=" + getHikePosition()[1] + "&maxResults=5&key=" + apiKey);
        return hikeInfo;
    }
    
    /**
     * Finds the latitude and longitude from the getApiInfo method call result.
     * @return a double array where [0] is the latitude and [1] is the longitude.
     * @throws JSONException 
     */
    public double[] getHikePosition() throws JSONException {
        String apiKey = "PDjIk1CuAfcFT0Bcr2w4Ep9uPRMH5T89";
        String hikePosition = getApiInfo("http://open.mapquestapi.com/geocoding/v1/address?key=" + apiKey + "&location=" + this.address.replace(" ", "+") + "," + this.state + "," + this.city + "," + this.postalCode);
        JSONObject apiJSON = new JSONObject(hikePosition);

        double[] hikeLatLng = new double[2];

        JSONArray hikeResultArray = apiJSON.getJSONArray("results");
        for (int i = 0; i < hikeResultArray.length(); i++) {

            JSONArray hikeLocationArray = hikeResultArray.getJSONObject(i).getJSONArray("locations");

            for(int j = 0; i < hikeLocationArray.length(); i++) {
                JSONObject displayLatLng = new JSONObject(hikeLocationArray.getJSONObject(j).getString("displayLatLng"));
                hikeLatLng[0] = Double.parseDouble(displayLatLng.getString("lat"));
                hikeLatLng[1] = Double.parseDouble(displayLatLng.getString("lng"));
            }
        }

        return hikeLatLng;

    }
    
    /**
     * Gets the API info from a specified URL. Since the result might not be JSON the method returns a String.
     * @param url The url of the API to get the info from.
     * @return A string of the API result.
     */
    private String getApiInfo(String url)  {
        try {
            URL oracle = new URL(url);
            BufferedReader in = new BufferedReader(
            new InputStreamReader(oracle.openStream()));

            String output = "";
            String inputLine;
            while ((inputLine = in.readLine()) != null) output += inputLine;
            in.close();
            return output;
        } catch(IOException e) {
            return "An error occurred in HikesFrame.getApiInfo() " + e;
        }
    }
    
    public String[] getHikesNames() {
        String[] hikesNames = new String[5];
        
        try {
            JSONObject hikeApiResult = new JSONObject(getHikeInfo());
            JSONArray hikesArray = hikeApiResult.getJSONArray("trails");
            
            for (int i = 0; i < hikesArray.length(); i++) {
                String hikeName = hikesArray.getJSONObject(i).getString("name");
                hikesNames[i] = hikeName;
                //System.out.println(hikeName);
            }
            return hikesNames;
        } catch(JSONException e) {
            System.out.println("A JSONException has occured in getHikesNames()." + e);
            return hikesNames;
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        hikeOneName = new javax.swing.JLabel();
        hikeTwoName = new javax.swing.JLabel();
        hikeThreeName = new javax.swing.JLabel();
        hikeFourName = new javax.swing.JLabel();
        hikeFiveName = new javax.swing.JLabel();
        hikeOneButton = new javax.swing.JRadioButton();
        hikeTwoButton = new javax.swing.JRadioButton();
        hikeThreeButton = new javax.swing.JRadioButton();
        hikeFourButton = new javax.swing.JRadioButton();
        hikeFiveButton = new javax.swing.JRadioButton();
        information = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hikeOneName.setText(getHikesNames()[0]);

        hikeTwoName.setText(getHikesNames()[1]);

        hikeThreeName.setText(getHikesNames()[2]);

        hikeFourName.setText(getHikesNames()[3]);

        hikeFiveName.setText(getHikesNames()[4]);

        information.setText("Choose a hike from below by clicking on a button to the right.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hikeFiveName, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                            .addComponent(hikeFourName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hikeThreeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hikeOneName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hikeTwoName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(103, 103, 103))
                    .addComponent(information))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hikeTwoButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hikeFiveButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hikeFourButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hikeThreeButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hikeOneButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(information)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hikeOneButton)
                    .addComponent(hikeOneName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hikeTwoButton)
                    .addComponent(hikeTwoName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hikeThreeName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(hikeThreeButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hikeFourButton)
                    .addComponent(hikeFourName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hikeFiveButton)
                    .addComponent(hikeFiveName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hikeOneName.getAccessibleContext().setAccessibleName("hikeOneName");

        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton hikeFiveButton;
    private javax.swing.JLabel hikeFiveName;
    private javax.swing.JRadioButton hikeFourButton;
    private javax.swing.JLabel hikeFourName;
    private javax.swing.JRadioButton hikeOneButton;
    private javax.swing.JLabel hikeOneName;
    private javax.swing.JRadioButton hikeThreeButton;
    private javax.swing.JLabel hikeThreeName;
    private javax.swing.JRadioButton hikeTwoButton;
    private javax.swing.JLabel hikeTwoName;
    private javax.swing.JLabel information;
    // End of variables declaration                   
}
