package com.hikingapp.view;

import com.hikingapp.model.HikesInfo;
import com.hikingapp.model.ModifyFile;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 * Deals with the user choosing which of the five hikes they want or if they want to import a hike.
 */
public class HikesFrame extends javax.swing.JFrame {

    private final HikesInfo HIKES;
    private HikeInfoFrame hikeInfoFrame;
    private String[] hikesNames;
    
    /**
     * Initializes the hikes and the form components.
     * @param hikesInfo The info of the hikes.
     */
    public HikesFrame(HikesInfo hikesInfo) {
        this.HIKES = hikesInfo;
        this.hikesNames = HIKES.getHikesNames(new String[5]);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        hikeTwoLabel = new javax.swing.JLabel();
        hikeThreeLabel = new javax.swing.JLabel();
        hikeFourLabel = new javax.swing.JLabel();
        hikeOneLabel = new javax.swing.JLabel();
        hikeFiveLabel = new javax.swing.JLabel();
        hikeOneButton = new javax.swing.JButton();
        hikeTwoButton = new javax.swing.JButton();
        hikeThreeButton = new javax.swing.JButton();
        hikeFourButton = new javax.swing.JButton();
        hikeFiveButton = new javax.swing.JButton();
        importHike = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("<html><h1>Choose a hike from below by clicking the button to the right.</h1></html>");

        hikeTwoLabel.setText(this.hikesNames[1]);

        hikeThreeLabel.setText(this.hikesNames[2]);

        hikeFourLabel.setText(this.hikesNames[3]);

        hikeOneLabel.setText(this.hikesNames[0]);

        hikeFiveLabel.setText(this.hikesNames[4]);

        hikeOneButton.setText("Select");
        hikeOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hikeOneButtonActionPerformed(evt);
            }
        });

        hikeTwoButton.setText("Select");
        hikeTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hikeTwoButtonActionPerformed(evt);
            }
        });

        hikeThreeButton.setText("Select");
        hikeThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hikeThreeButtonActionPerformed(evt);
            }
        });

        hikeFourButton.setText("Select");
        hikeFourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hikeFourButtonActionPerformed(evt);
            }
        });

        hikeFiveButton.setText("Select");
        hikeFiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hikeFiveButtonActionPerformed(evt);
            }
        });

        importHike.setText("Import Hike");
        importHike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importHikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hikeOneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(hikeTwoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hikeThreeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hikeFourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hikeOneButton)
                                    .addComponent(hikeTwoButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(hikeThreeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(hikeFourButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hikeFiveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hikeFiveButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(importHike)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importHike)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hikeOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hikeOneButton))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hikeTwoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hikeTwoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hikeThreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hikeThreeButton))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hikeFourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hikeFourButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hikeFiveLabel)
                    .addComponent(hikeFiveButton))
                .addContainerGap())
        );

        titleLabel.getAccessibleContext().setAccessibleName("hikesFrameTitle");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Shows the HikeInfoFrame and hides the current frame.
     * @param hikeInfo The info pertaining to the hike that the user chose.
     */
    private void showHikeInfoFrame(HashMap<String, String> hikeInfo) {
        hikeInfoFrame = new HikeInfoFrame(hikeInfo);
        hikeInfoFrame.setVisible(true);
        this.setVisible(false);
    }
    
    /**
     * Is clicked if the user wants to choose the first hike.
     * @param evt The parameter passed in when the action is performed.
     */
    private void hikeOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hikeOneButtonActionPerformed
        showHikeInfoFrame(HIKES.getChosenHikeInfo(this.hikesNames[0]));
    }//GEN-LAST:event_hikeOneButtonActionPerformed

    /**
     * Is clicked if the user wants to choose the second hike.
     * @param evt The parameter passed in when the action is performed.
     */
    private void hikeTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hikeTwoButtonActionPerformed
        showHikeInfoFrame(HIKES.getChosenHikeInfo(this.hikesNames[1]));
    }//GEN-LAST:event_hikeTwoButtonActionPerformed

    /**
     * Is clicked if the user wants to choose the third hike.
     * @param evt The parameter passed in when the action is performed.
     */
    private void hikeThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hikeThreeButtonActionPerformed
        showHikeInfoFrame(HIKES.getChosenHikeInfo(this.hikesNames[2]));
    }//GEN-LAST:event_hikeThreeButtonActionPerformed

    /**
     * Is clicked if the user wants to choose the fourth hike.
     * @param evt The parameter passed in when the action is performed.
     */
    private void hikeFourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hikeFourButtonActionPerformed
        showHikeInfoFrame(HIKES.getChosenHikeInfo(this.hikesNames[3]));
    }//GEN-LAST:event_hikeFourButtonActionPerformed

    /**
     * Is clicked if the user wants to choose the fifth hike.
     * @param evt The parameter passed in when the action is performed.
     */
    private void hikeFiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hikeFiveButtonActionPerformed
        showHikeInfoFrame(HIKES.getChosenHikeInfo(this.hikesNames[4]));
    }//GEN-LAST:event_hikeFiveButtonActionPerformed

    /**
     * Fires if the import hike button has been fired which then prompts the user for the file to import.
     * @param evt The parameter that was passed in when the action is performed.
     */
    private void importHikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importHikeActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File chosenFile = fileChooser.getSelectedFile();
            
            HashMap<String, String> importedHikeInformation = new HashMap<>();
            //showHikeInfoFrame(importedHikInformation);
            
            JSONParser parser = new JSONParser();
            ModifyFile modifier = new ModifyFile();

            try {
                String fileText = new String(modifier.readFromFile(chosenFile, 0, (int) chosenFile.length()));
                JSONObject jsonHikeInfo = (JSONObject) parser.parse(fileText);

                importedHikeInformation.put("name", (String) jsonHikeInfo.get("name"));
                importedHikeInformation.put("summary", (String) jsonHikeInfo.get("summary"));
                importedHikeInformation.put("difficulty", (String) jsonHikeInfo.get("difficulty"));
                importedHikeInformation.put("stars", (String) jsonHikeInfo.get("stars"));
                importedHikeInformation.put("starVotes", (String) jsonHikeInfo.get("starVotes"));
                importedHikeInformation.put("location", (String) jsonHikeInfo.get("location"));
                importedHikeInformation.put("imgUrl", (String) jsonHikeInfo.get("imgUrl"));
                importedHikeInformation.put("length", (String) jsonHikeInfo.get("length"));
                importedHikeInformation.put("ascent", (String) jsonHikeInfo.get("ascent"));
                importedHikeInformation.put("descent", (String) jsonHikeInfo.get("descent"));
                importedHikeInformation.put("high", (String) jsonHikeInfo.get("high"));
                importedHikeInformation.put("low", (String) jsonHikeInfo.get("low"));
                importedHikeInformation.put("conditionStatus", (String) jsonHikeInfo.get("conditionStatus"));
                importedHikeInformation.put("conditionDetails", (String) jsonHikeInfo.get("conditionDetails"));
                importedHikeInformation.put("conditionDate", (String) jsonHikeInfo.get("conditionDate"));
                importedHikeInformation.put("url", (String) jsonHikeInfo.get("url"));
                
                showHikeInfoFrame(importedHikeInformation);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(HikesFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException | ParseException ex) {
                Logger.getLogger(HikesFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_importHikeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hikeFiveButton;
    private javax.swing.JLabel hikeFiveLabel;
    private javax.swing.JButton hikeFourButton;
    private javax.swing.JLabel hikeFourLabel;
    private javax.swing.JButton hikeOneButton;
    private javax.swing.JLabel hikeOneLabel;
    private javax.swing.JButton hikeThreeButton;
    private javax.swing.JLabel hikeThreeLabel;
    private javax.swing.JButton hikeTwoButton;
    private javax.swing.JLabel hikeTwoLabel;
    private javax.swing.JButton importHike;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
